/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import database.DBConnection;
import interfaces.GalleryProvider;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import models.Wallpaper;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Nice
 */
public class DetailFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetailFrame.class.getName());

    /**
     * Creates new form DetailFrame
     */

    private final int currentUserId;
    private final Wallpaper wallpaperInfo;
    private final JFrame mainFrame;

    public DetailFrame(Wallpaper wp, int currentUserId, JFrame mainFrame, File fileGambar) {
        this.wallpaperInfo = wp;
        this.mainFrame = mainFrame;
        this.currentUserId = currentUserId;

        initComponents();
        this.setTitle(wallpaperInfo.getTitle());
        jButtonUpdate.setVisible(false);
        boolean isAdmin = (mainFrame instanceof ManageFrame) && currentUserId == 1;
        boolean isUser  = (mainFrame instanceof ProfileFrame) && currentUserId == wallpaperInfo.getUserId();   
        boolean isGuest = (currentUserId == -1);
        
        if (isGuest) {
            jButtonDelete.setVisible(false);
            jButtonDownload.setVisible(true);
            jButtonDownload.setPreferredSize(new java.awt.Dimension(762, 40));
        } else {
            jButtonDownload.setVisible(true);
            jButtonDownload.setPreferredSize(new java.awt.Dimension(382, 40));

            if (isAdmin) {
                jButtonUpdate.setVisible(true);  
                jButtonDelete.setVisible(true);
                jButtonDelete.setPreferredSize(new java.awt.Dimension(378, 40));
            } else if (isUser) {
                jButtonDelete.setVisible(true);
                jButtonDelete.setPreferredSize(new java.awt.Dimension(378, 40));
            } else {
                jButtonDelete.setVisible(false);
                jButtonDownload.setPreferredSize(new java.awt.Dimension(762, 40));
            }
        }

        jButtonDownload.setContentAreaFilled(false);
        jButtonDelete.setContentAreaFilled(false);
        jButtonUpdate.setContentAreaFilled(false);

        getContentPane().setBackground(new java.awt.Color(41, 41, 41));
        showWallpaperDetail(fileGambar);
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonDownload = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabelImageTitle = new javax.swing.JLabel();
        jLabelUploaderName = new javax.swing.JLabel();
        jLabelCategory = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();
        jButtonUpdate = new javax.swing.JButton();
        jLabelUpdateTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(800, 800));
        setResizable(false);

        jLabelImage.setBackground(new java.awt.Color(255, 255, 255));
        jLabelImage.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImage.setMaximumSize(new java.awt.Dimension(800, 500));
        jLabelImage.setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel2.setBackground(new java.awt.Color(41, 41, 41));
        jPanel2.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 165));

        jButtonDownload.setBackground(new java.awt.Color(41, 41, 41));
        jButtonDownload.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jButtonDownload.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDownload.setText("Download");
        jButtonDownload.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDownload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDownload.addActionListener(this::jButtonDownloadActionPerformed);

        jButtonDelete.setBackground(new java.awt.Color(41, 41, 41));
        jButtonDelete.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Delete");
        jButtonDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jLabelImageTitle.setBackground(new java.awt.Color(255, 255, 255));
        jLabelImageTitle.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabelImageTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImageTitle.setText("image_nama");

        jLabelUploaderName.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jLabelUploaderName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUploaderName.setText("username");
        jLabelUploaderName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelUploaderName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUploaderNameMouseClicked(evt);
            }
        });

        jLabelCategory.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jLabelCategory.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCategory.setText("category");

        jLabelDate.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jLabelDate.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDate.setText("date");

        jLabelDescription.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jLabelDescription.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescription.setText("description text");
        jLabelDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButtonUpdate.setBackground(new java.awt.Color(41, 41, 41));
        jButtonUpdate.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setText("Update");
        jButtonUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUpdate.addActionListener(this::jButtonUpdateActionPerformed);

        jLabelUpdateTime.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jLabelUpdateTime.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUpdateTime.setText("update date");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelUploaderName)
                                    .addComponent(jLabelImageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelUpdateTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                                    .addComponent(jLabelCategory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(367, Short.MAX_VALUE)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabelImageTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUploaderName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelUpdateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCategory)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        File fileGambar = new File("src/uploads/" + wallpaperInfo.getImagePath());
        UpdateFrame updatePage = new UpdateFrame (wallpaperInfo, currentUserId, mainFrame, fileGambar);
        updatePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDownloadActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (this.wallpaperInfo == null || this.wallpaperInfo.getImagePath() == null) {
            JOptionPane.showMessageDialog(this, "Data gambar tidak valid! tidak ada di database", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        File fileWallpaper = new File("src/uploads/" + this.wallpaperInfo.getImagePath());

        if (!fileWallpaper.exists()) {
            JOptionPane.showMessageDialog(this, """
                    Gagal mendownload! File asli tidak ditemukan di folder: "src/uploads/"
                    Kemungkinan file telah terhapus atau dipindahkan secara manual.""",
                    "File Tidak Ditemukan",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Pilih Lokasi Simpan Wallpaper");

        String imagePath = this.wallpaperInfo.getImagePath();
        String extension = imagePath.substring(imagePath.lastIndexOf("."));

        String namaFileBersih = this.wallpaperInfo.getTitle().replaceAll("[^a-zA-Z0-9]", "_") + extension;
        fileChooser.setSelectedFile(new File(namaFileBersih));

        int pilihanUser = fileChooser.showSaveDialog(this);

        if (pilihanUser == JFileChooser.APPROVE_OPTION) {
            File fileTujuan = fileChooser.getSelectedFile();

            try {
                Files.copy(fileWallpaper.toPath(), fileTujuan.toPath(), StandardCopyOption.REPLACE_EXISTING);
                JOptionPane.showMessageDialog(this, "Wallpaper berhasil diunduh!", "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal mengunduh: " + e.getMessage(), "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (this.wallpaperInfo == null) {
            JOptionPane.showMessageDialog(this, "Data wallpaper tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int deleteConfirmation = JOptionPane.showConfirmDialog(this, "Delete Wallpaper " + wallpaperInfo.getTitle(),
                "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (deleteConfirmation != JOptionPane.YES_OPTION) {
            return;
        }

        // delete dari database
        String deleteQuerySQL = "DELETE FROM artworks WHERE id = ?";

        try (Connection con = DBConnection.getConnection();
                PreparedStatement deletePstmt = con.prepareStatement(deleteQuerySQL)) {

            deletePstmt.setInt(1, wallpaperInfo.getId());

            int barisTerdelete = deletePstmt.executeUpdate();

            if (barisTerdelete > 0) {

                // delete dari folder uploads
                File imageFilePath = new File("src/uploads/" + wallpaperInfo.getImagePath());

                if (imageFilePath.exists()) {
                    imageFilePath.delete();
                } else {
                    System.out.println("File fisik tidak ditemukan di folder uploads, hanya membersihkan data database.");
                }

                JOptionPane.showMessageDialog(this, "Wallpaper berhasil dihapus");

                this.setVisible(false);
                this.dispose();

                if (this.mainFrame != null) {
                    this.mainFrame.setVisible(true);
                    if (this.mainFrame instanceof ProfileFrame profileFrame)profileFrame.showGalleryWallpaperUser();
                    else if(this.mainFrame instanceof ManageFrame manageFrame)manageFrame.showWallpaperGalleryAll();
                     
                }

            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus! Data tidak ditemukan di database.", "Peringatan",
                        JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan database: " + e.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }

    private void jLabelUploaderNameMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelUploaderNameMouseClicked
        // TODO add your handling code here:
        new PublicProfileFrame(wallpaperInfo.getUserId(), currentUserId).setVisible(true);
    }

    private void showWallpaperDetail(File fileGambar) {

        int lebar = 800;
        int panjang = 500;

        if (wallpaperInfo != null) {
            String uploader = GalleryProvider.getUsernameFromId(wallpaperInfo.getUserId());
            String uploaderCapitalized = uploader.substring(0, 1).toUpperCase() + uploader.substring(1);
            String title = wallpaperInfo.getTitle();
            String[] words = title.split(" ");
            StringBuilder capitalizedTitle = new StringBuilder();

            for (String word : words) {
                if (!word.isEmpty()) {
                    capitalizedTitle.append(word.substring(0, 1).toUpperCase())
                            .append(word.substring(1).toLowerCase())
                            .append(" ");
                }
            }
            
            java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd MMMM yyyy", new java.util.Locale("id", "ID"));
            
            String rawDate = wallpaperInfo.getTimeAdded().substring(0, wallpaperInfo.getTimeAdded().indexOf(' '));
            java.time.LocalDate date = java.time.LocalDate.parse(rawDate);             
            String formattedDate = date.format(formatter);
            
            String formattedUpdateDate = "";
            if (wallpaperInfo.getTimeUpdated() != null && !wallpaperInfo.getTimeUpdated().isEmpty()) {
                String rawUpdateDate = wallpaperInfo.getTimeUpdated().substring(0, wallpaperInfo.getTimeUpdated().indexOf(' '));
                java.time.LocalDate updateDate = java.time.LocalDate.parse(rawUpdateDate);
                formattedUpdateDate = updateDate.format(formatter);
            }

            jLabelImageTitle.setText(capitalizedTitle.toString().trim());
            jLabelUploaderName.setText("<html><b>Uploaded By:</b>&nbsp;&nbsp;&nbsp;&nbsp;" + uploaderCapitalized + "</html>");
            jLabelCategory.setText("<html><b>Category:</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+ wallpaperInfo.getCategory() + "</html>");
            jLabelDescription.setText(wallpaperInfo.getDescription());
            jLabelDate.setText("<html><b>Created At:</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+ formattedDate + "</html>");
            jLabelUpdateTime.setText("<html><b>Updated At:</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" + formattedUpdateDate + "</html>");
            
            try {

                ImageIcon selectedIcon;

                if (fileGambar.exists() && this.wallpaperInfo.getImagePath() != null) {

                    selectedIcon = new ImageIcon(fileGambar.getAbsolutePath());

                } else {

                    selectedIcon = new ImageIcon("src/uploads/default.jpg");

                }

                Image scaledImage = selectedIcon.getImage().getScaledInstance(lebar, panjang, Image.SCALE_SMOOTH);

                jLabelImage.setIcon(new ImageIcon(scaledImage));

            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            System.out.print("Error");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDownload;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelCategory;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelImageTitle;
    private javax.swing.JLabel jLabelUpdateTime;
    private javax.swing.JLabel jLabelUploaderName;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
