/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import database.DBConnection;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import models.Wallpaper;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import static models.Wallpaper.getUsernameById;
/**
 *
 * @author Nice
 */
public class DetailFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetailFrame.class.getName());

    /**
     * Creates new form DetailFrame
     */
    
   private final Wallpaper wallpaperInfo;
   private final JFrame mainFrame;
    
    public DetailFrame(Wallpaper wp,  int currentUserId, JFrame mainFrame, File fileImage) {
        this.wallpaperInfo = wp;
        this.mainFrame = mainFrame;       
        
        initComponents();
        
        this.setSize(800, 615);
        this.setTitle(wallpaperInfo.getTitle());
        
        if (this.mainFrame instanceof ProfileFrame && currentUserId == wallpaperInfo.getUserId()) {
            jButtonDelete.setVisible(true);  
        } else {
            jButtonDelete.setVisible(false); 
        }

        showWallpaperDetail(fileImage);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonDownload = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabelImageTitle = new javax.swing.JLabel();
        jLabelUploaderName = new javax.swing.JLabel();
        jLabelCategory = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setResizable(false);

        jLabelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImage.setMaximumSize(new java.awt.Dimension(800, 500));
        jLabelImage.setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 165));

        jButtonDownload.setText("Download");
        jButtonDownload.addActionListener(this::jButtonDownloadActionPerformed);

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jLabelImageTitle.setText("image_nama");

        jLabelUploaderName.setText("username");

        jLabelCategory.setText("category");

        jLabelDate.setText("date");

        jLabel4.setText("Description :");

        jLabelDescription.setText("description text");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImageTitle)
                    .addComponent(jLabelUploaderName)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCategory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(122, 122, 122)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130)
                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonDownload)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImageTitle)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabelUploaderName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelCategory)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDate))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonDownload)
                                .addComponent(jButtonDelete))
                            .addGap(34, 34, 34)))
                    .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownloadActionPerformed
        // TODO add your handling code here:
        if (this.wallpaperInfo == null || this.wallpaperInfo.getImagePath() == null) {
            JOptionPane.showMessageDialog(this, "Data gambar tidak ada di database?", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        File fileWallpaper = new File("src/uploads/" + this.wallpaperInfo.getImagePath());
            
        if (!fileWallpaper.exists()) {
        JOptionPane.showMessageDialog(this, """
        Gagal mendownload! File asli tidak ditemukan di folder: "src/uploads/"
        Kemungkinan file telah terhapus atau dipindahkan secara manual.""", 
        "File Tidak Ditemukan", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        //Memilih letak wallpaper didownload
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Pilih Lokasi Simpan Wallpaper");
        
        String changedFileName = this.wallpaperInfo.getTitle().replace(" ", "_") + ".jpg";
        fileChooser.setSelectedFile(new File(fileChooser.getCurrentDirectory(), changedFileName));      
      
        int pilihanUser = fileChooser.showSaveDialog(this);
        
        if (pilihanUser == JFileChooser.APPROVE_OPTION) {
           
            File destinationFile = fileChooser.getSelectedFile();
            
            try {               
                Files.copy(fileWallpaper.toPath(), destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                JOptionPane.showMessageDialog(this, "Wallpaper berhasil diunduh!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException  e) {
                JOptionPane.showMessageDialog(this, "Gagal mengunduh Wallpaper: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_jButtonDownloadActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        if (this.wallpaperInfo == null) {
        JOptionPane.showMessageDialog(this, "Data wallpaper tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        int deleteConfirmation = JOptionPane.showConfirmDialog(this, "Delete Wallpaper " + wallpaperInfo.getTitle(), "Konfirmasi",JOptionPane.YES_NO_OPTION);
      
        if(deleteConfirmation != JOptionPane.YES_OPTION){
            return;
        }
        
        //delete dari database
        String deleteQuerySQL = "DELETE FROM artworks WHERE id = ?";
        
        try (Connection con = DBConnection.getConnection();
            PreparedStatement deletePstmt = con.prepareStatement(deleteQuerySQL)){
        
            deletePstmt.setInt(1, wallpaperInfo.getId());

            int barisTerdelete = deletePstmt.executeUpdate();
            
            if(barisTerdelete > 0) {
                
                //delete dari folder uploads
                File imageFilePath = new File("src/uploads/" + wallpaperInfo.getImagePath());

                if(imageFilePath.exists()) {
                    imageFilePath.delete();
                } else {    
                    System.out.println("File fisik tidak ditemukan di folder uploads, hanya membersihkan data database.");
                }                
                
                JOptionPane.showMessageDialog(this, "Wallpaper berhasil dihapus");
                
                this.setVisible(false);
                this.dispose();
                
                if (this.mainFrame != null) {
                    this.mainFrame.setVisible(true);
                    ((ProfileFrame)this.mainFrame).showGalleryWallpaperUser();
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus! Data tidak ditemukan di database.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
          
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
      
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void showWallpaperDetail(File fileImage){
        
        int lebar = 800;
        int panjang = 500;
        
        if (wallpaperInfo == null) {
            System.out.println("Error: Data wallpaper tidak ditemukan.");
            return;
        }
             
            jLabelImageTitle.setText(wallpaperInfo.getTitle());
            jLabelUploaderName.setText("Uploaded By: " + getUsernameById(wallpaperInfo.getUserId()));
            jLabelCategory.setText("Category:" + wallpaperInfo.getCategory());         
            jLabelDescription.setText(wallpaperInfo.getDescription());
            jLabelDate.setText("Created At: " + wallpaperInfo.getTimeAdded().substring(0,wallpaperInfo.getTimeAdded().indexOf(' ')));
           
            try {
                
                    ImageIcon selectedImage;
                    
                    if (fileImage.exists() && this.wallpaperInfo.getImagePath() != null) {
                        
                        selectedImage = new ImageIcon(fileImage.getAbsolutePath());

                        
                    } else {
                        
                        selectedImage = new ImageIcon("src/uploads/default.jpg");
                        
                    }
                    
                    Image scaledImage = selectedImage.getImage().getScaledInstance(lebar, panjang, Image.SCALE_SMOOTH);

                    jLabelImage.setIcon(new ImageIcon(scaledImage));
                   
                } catch (Exception e) {
                    e.printStackTrace();
                }        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDownload;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCategory;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelImageTitle;
    private javax.swing.JLabel jLabelUploaderName;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
