/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import components.WallpaperCard;
import database.DBConnection;
import interfaces.GalleryProvider;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import models.Wallpaper;
import models.WallpaperPublic;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Nice
 */
public class HomeFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeFrame.class.getName());

    /**
     * Creates new form HomeFrame
     */
    
    private int currentUserId;
    private String currentUsername;
    private boolean isUserLoggedIn = false;

    public HomeFrame(boolean isLogin, int userID, String username) { 
        this.currentUserId = -1;
        this.currentUsername = "  GUEST";

        if (isLogin) {
           this.isUserLoggedIn = isLogin;
           this.currentUserId = userID;
           this.currentUsername = "  " + username;         
        }

        initComponents();   
        jScrollPanePublicWallpaperGallery.setBorder(null);
        jScrollPanePublicWallpaperGallery.getVerticalScrollBar().setPreferredSize(new java.awt.Dimension(0, 0));
        jScrollPanePublicWallpaperGallery.getHorizontalScrollBar().setPreferredSize(new java.awt.Dimension(0, 0));
        jScrollPanePublicWallpaperGallery.getVerticalScrollBar().setUnitIncrement(20);
        jScrollPanePublicWallpaperGallery.setWheelScrollingEnabled(true);
        getContentPane().setBackground(new java.awt.Color(41, 41, 41));
        setResizable(false);
        setLocationRelativeTo(null);

        profileBtn.setContentAreaFilled(false);
        uploadBtn.setContentAreaFilled(false);
        loginBtn.setContentAreaFilled(false);
        jButtonReset.setContentAreaFilled(false);
              
        profileBtn.setVisible(isUserLoggedIn);
        uploadBtn.setVisible(isUserLoggedIn);
        loginBtn.setVisible(isUserLoggedIn == false);
        
        jLabelUsernameHomePage.setText(currentUsername.toUpperCase());       
        getWallpaperCategoryList();
        showWallpaperGalleryAll();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUsernameHomePage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        profileBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        uploadBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxCategory = new javax.swing.JComboBox<>();
        jButtonReset = new javax.swing.JButton();
        jScrollPanePublicWallpaperGallery = new javax.swing.JScrollPane();
        jPanelHomeGallery = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Page");
        setBackground(new java.awt.Color(41, 41, 41));
        setPreferredSize(new java.awt.Dimension(1080, 660));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(41, 41, 41));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 120));

        jLabelUsernameHomePage.setBackground(new java.awt.Color(255, 255, 255));
        jLabelUsernameHomePage.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabelUsernameHomePage.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsernameHomePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/prfl_ic.png"))); // NOI18N
        jLabelUsernameHomePage.setText("  USER!");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome! Find ideas you’ll love.");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Discover ideas, save inspiration, and bring your imagination.");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoPixelPaint.png"))); // NOI18N

        profileBtn.setBackground(new java.awt.Color(0, 0, 0));
        profileBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        profileBtn.setForeground(new java.awt.Color(255, 255, 255));
        profileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile_icon.png"))); // NOI18N
        profileBtn.setText("Profile");
        profileBtn.setAlignmentY(0.0F);
        profileBtn.setBorder(null);
        profileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBtnMouseClicked(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(0, 0, 0));
        loginBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lgin_con.png"))); // NOI18N
        loginBtn.setText(" Sign In");
        loginBtn.setAlignmentY(0.0F);
        loginBtn.setBorder(null);
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addGap(22, 22, 22)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelUsernameHomePage))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(21, 21, 21)))
                            .addGap(19, 19, 19))
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelUsernameHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
        );

        jPanel2.setBackground(new java.awt.Color(41, 41, 41));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Visual Gallery");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Explore millions of visual ideas and find the best inspiration for you.");

        uploadBtn.setBackground(new java.awt.Color(0, 0, 0));
        uploadBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        uploadBtn.setForeground(new java.awt.Color(255, 255, 255));
        uploadBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unggah.png"))); // NOI18N
        uploadBtn.setText(" Uploads");
        uploadBtn.setAlignmentY(0.0F);
        uploadBtn.setBorder(null);
        uploadBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uploadBtn.addActionListener(this::uploadBtnActionPerformed);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Choose category to filter :");

        jComboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCategory.addActionListener(this::jComboBoxCategoryActionPerformed);

        jButtonReset.setBackground(new java.awt.Color(41, 41, 41));
        jButtonReset.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReset.setText("Reset");
        jButtonReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReset.addActionListener(this::jButtonResetActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 86, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonReset)
                .addGap(42, 42, 42)
                .addComponent(uploadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReset))
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(uploadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jScrollPanePublicWallpaperGallery.setBackground(new java.awt.Color(41, 41, 41));
        jScrollPanePublicWallpaperGallery.setAlignmentX(0.0F);
        jScrollPanePublicWallpaperGallery.setAlignmentY(0.0F);
        jScrollPanePublicWallpaperGallery.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPanePublicWallpaperGallery.setRowHeaderView(null);

        jPanelHomeGallery.setBackground(new java.awt.Color(41, 41, 41));
        jPanelHomeGallery.setAlignmentX(0.0F);
        jPanelHomeGallery.setAlignmentY(0.0F);
        jPanelHomeGallery.setLayout(new java.awt.GridLayout(1, 3));
        jScrollPanePublicWallpaperGallery.setViewportView(jPanelHomeGallery);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPanePublicWallpaperGallery)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPanePublicWallpaperGallery, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("PixelPaint Gallery");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void uploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg"));
        
        int result = fileChooser.showOpenDialog(this);
        
        if (result != JFileChooser.APPROVE_OPTION) {
            return;
        }
        
        File fileWallpaper = fileChooser.getSelectedFile();
        File targetDirectory = new File("src/uploads");
        
        if (!targetDirectory.exists()) {
            targetDirectory.mkdirs();
        }
        
        String title = "";                   
            while(title.trim().length() > 15 || title.trim().isEmpty()) {               
            title = JOptionPane.showInputDialog(this, "(15 karakter!) Masukkan Judul Wallpaper:");
                
                if (title.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Wallpaper harus diberikan title!");
                } else if (title.length() > 15) {
                    JOptionPane.showMessageDialog(this, "Wallpaper title terlalu panjang!");            
                }   
            } 
        
        String description = JOptionPane.showInputDialog(this, "(Boleh di skip!)Masukkan Deskripsi:");       
            if (!description.trim().isEmpty()) {
                while (description.length() > 20) {

                    if (description.length() > 20) {
                        JOptionPane.showMessageDialog(this, "Wallpaper description terlalu panjang!");
                    }   

                    description = JOptionPane.showInputDialog(this, "(Boleh di skip!)Masukkan Deskripsi:");
                }        
            }
        
        String category = getValidatedCategoryFromUser();      
        if (category == null) {
            JOptionPane.showMessageDialog(this, "Wallpaper harus diberikan Category!");
            return;
        }
        
        String uniqueFileName = currentUserId + "_" + System.currentTimeMillis() + "_" + (fileWallpaper.getName().replace(" ", "_"));
        File destinationFile = new File(targetDirectory, uniqueFileName);
             
            String insertQuerySQL = "INSERT INTO artworks (title, description, category, image_path, user_id) VALUES (?, ?, ?, ?, ?)";
            try (Connection con = DBConnection.getConnection();
                PreparedStatement AddWallapaperPstmt = con.prepareStatement(insertQuerySQL)) {
                AddWallapaperPstmt.setString(1, title.trim());
                AddWallapaperPstmt.setString(2, description != null ? description.trim() : "");
                AddWallapaperPstmt.setString(3, category.trim().toLowerCase());
                AddWallapaperPstmt.setString(4, uniqueFileName);
                AddWallapaperPstmt.setInt(5, currentUserId);
                
                // Proses copy file secara langsung ke folder uploads
                Files.copy(fileWallpaper.toPath(), destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                AddWallapaperPstmt.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Wallpaper berhasil diunggah!");
                getWallpaperCategoryList();
                showWallpaperGalleryAll();
            }
            
         catch (IOException | SQLException e) {
             if (destinationFile.exists()) {
                destinationFile.delete();
            }
            JOptionPane.showMessageDialog(this, "Gagal memproses unggahan: " + e.getMessage());
        }
    }//GEN-LAST:event_uploadBtnActionPerformed

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        // TODO add your handling code here:
         new LoginFrame().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_loginBtnMouseClicked

    private void profileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnMouseClicked
        // TODO add your handling code here:
        new ProfileFrame(currentUserId, currentUsername, "").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileBtnMouseClicked

    private void jComboBoxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryActionPerformed
        // TODO add your handling code here:
        String selectedCategory = (String) jComboBoxCategory.getSelectedItem();

        GalleryProvider gallery = new WallpaperPublic(); 
        List<Wallpaper> daftarWallpaper =  gallery.getGalleryWallpaper(currentUserId);
        List<Wallpaper> filteredDaftarWallpaper = gallery.filterByCategory(daftarWallpaper, selectedCategory);   

        jPanelHomeGallery.removeAll();

           for (Wallpaper wp : filteredDaftarWallpaper) {
               WallpaperCard card = new WallpaperCard(wp, currentUserId, this);
               jPanelHomeGallery.add(card);
            }    

       jPanelHomeGallery.revalidate();
       jPanelHomeGallery.repaint();
    }//GEN-LAST:event_jComboBoxCategoryActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        showWallpaperGalleryAll();
    }//GEN-LAST:event_jButtonResetActionPerformed
    
    private String getValidatedCategoryFromUser() {
           
        ArrayList<String> listCategory = new ArrayList<>();
        
        for (int i = 0; i < jComboBoxCategory.getItemCount(); i++) {
            Object item = jComboBoxCategory.getItemAt(i);
            if (item != null) {
                listCategory.add(item.toString());
            }
        }

        String optionCategoryBaru = "+ Tambah Kategori Baru...";
        listCategory.add(optionCategoryBaru);
        
        JComboBox <String> comboBoxInputCategory = new JComboBox<>(listCategory.toArray(new String[0]));
        
        //Lamda Function
        comboBoxInputCategory.addActionListener(e -> {
            
            String result;          
            String selectedCategory = (String) comboBoxInputCategory.getSelectedItem();
            
            if (selectedCategory.equals(optionCategoryBaru)) {

                String newCategory = JOptionPane.showInputDialog(this, "Masukkan Nama Kategori Baru:");

                if (newCategory == null || newCategory.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Kategori baru tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    comboBoxInputCategory.setSelectedIndex(0);
                    return;
                }

                String input = newCategory.toLowerCase().replaceAll("\\s+", "");
                String categoryCheck = "";
                boolean isDuplicate = false;

                for (String exisingCategory : listCategory) {                
                    if (!exisingCategory.equals(optionCategoryBaru)){
                        
                        String category = exisingCategory.toLowerCase().replaceAll("\\s+", "");
                        if (input.equals(category)) {
                            isDuplicate = true;
                            categoryCheck = exisingCategory;
                            break;
                        }
                        
                    }          
                }

                if (isDuplicate) {
                    JOptionPane.showMessageDialog(this, 
                        "Kategori " + newCategory + " sama dengan " + categoryCheck + " yang sudah ada.\n" +
                        "Silakan pilih langsung '" + categoryCheck + "' pada Dropdown!", 
                        "Kategori Sudah Ada", JOptionPane.WARNING_MESSAGE);
                }
                
                result = (Character.toUpperCase(input.charAt(0)) + input.substring(1)).trim();
                int indexCategoryBaru = comboBoxInputCategory.getItemCount() - 1 ;               
                comboBoxInputCategory.insertItemAt(result,indexCategoryBaru);
                comboBoxInputCategory.setSelectedItem(result);
            }                      
        });

        int dialogConfirm = JOptionPane.showConfirmDialog(
            this, 
            comboBoxInputCategory, 
            "Pilih Kategori Wallpaper", 
            JOptionPane.OK_CANCEL_OPTION, 
            JOptionPane.PLAIN_MESSAGE
        );
        
        if (dialogConfirm == JOptionPane.OK_OPTION) {
            String finalSelection = (String) comboBoxInputCategory.getSelectedItem();

            if (optionCategoryBaru.equals(finalSelection)) {
                JOptionPane.showMessageDialog(this, "Silakan pilih kategori yang valid!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return null;
            }

            return finalSelection.toLowerCase();
        }

        return null;    
    }
    
    private void getWallpaperCategoryList() {        
        String getByCategorySQL = "SELECT DISTINCT LOWER(category) AS category_name FROM artworks";       
        try (Connection con = DBConnection.getConnection();
            PreparedStatement listCategory = con.prepareStatement(getByCategorySQL)) {
            
            ResultSet resListCategory = listCategory.executeQuery();          
            jComboBoxCategory.removeAllItems();
            
            while (resListCategory.next()) {            
                jComboBoxCategory.addItem(Character.toUpperCase(resListCategory.getString("category_name").charAt(0)) + resListCategory.getString("category_name").substring(1));
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "gagal mendapat category", "Database Error" ,JOptionPane.ERROR_MESSAGE);
        }       
    }
    
    private void showWallpaperGalleryAll () {       
        jPanelHomeGallery.removeAll();
        jPanelHomeGallery.setLayout(new GridLayout(0, 4, 10, 15));
        jPanelHomeGallery.setBorder(BorderFactory.createEmptyBorder(10, 20, 50, 15));
        
        //gallery public
        GalleryProvider gallery = new WallpaperPublic();        
        List<Wallpaper> daftarWallpaper =  gallery.getGalleryWallpaper(currentUserId);
        
        for (Wallpaper wp : daftarWallpaper) {
            WallpaperCard card = new WallpaperCard(wp, currentUserId, this);
            jPanelHomeGallery.add(card);
        }
        
        JPanel wrapper = new JPanel(new BorderLayout());        
        wrapper.setBackground(jPanelHomeGallery.getBackground());
        wrapper.add(jPanelHomeGallery, BorderLayout.NORTH);
        
        jScrollPanePublicWallpaperGallery.setViewportView(wrapper);
        jScrollPanePublicWallpaperGallery.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        jScrollPanePublicWallpaperGallery.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPanePublicWallpaperGallery.getVerticalScrollBar().setUnitIncrement(20);

        wrapper.revalidate();        
        wrapper.repaint();      
        jPanelHomeGallery.revalidate();
        jPanelHomeGallery.repaint();         
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeFrame(false,0,"").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReset;
    private javax.swing.JComboBox<String> jComboBoxCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelUsernameHomePage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelHomeGallery;
    private javax.swing.JScrollPane jScrollPanePublicWallpaperGallery;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton profileBtn;
    private javax.swing.JButton uploadBtn;
    // End of variables declaration//GEN-END:variables
}
