/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import components.WallpaperCard;
import database.DBConnection;
import interfaces.GalleryProvider;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import models.Wallpaper;
import models.WallpaperPublic;

/**
 *
 * @author Nice
 */
public class HomeFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeFrame.class.getName());

    /**
     * Creates new form HomeFrame
     */
    
    private int currentUserId;
    private String currentUsername;
    private boolean isUserLoggedIn = false;

    public HomeFrame(boolean isLogin, int userID, String username) { 
        this.currentUserId = 0;
        this.currentUsername = "Guest";      

        if (isLogin) {
           this.isUserLoggedIn = isLogin;
           this.currentUserId = userID;
           this.currentUsername = username;              
        }

        initComponents();   
        setResizable(false);
        setLocationRelativeTo(null);
        
        getWallpaperCategoryList();
        ShowWallpaperGalleryAll();
        
        jLabelUsernameHomePage.setText(currentUsername);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelProfileIcon = new javax.swing.JLabel();
        jLabelUsernameHomePage = new javax.swing.JLabel();
        jLabelTotalWallpaperHomePage = new javax.swing.JLabel();
        jComboBoxCategory = new javax.swing.JComboBox<>();
        jScrollPanePublicWallpaperGallery = new javax.swing.JScrollPane();
        jPanelHomeGallery = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Page");
        setPreferredSize(new java.awt.Dimension(1080, 660));

        jLabelProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-profile-48.png"))); // NOI18N
        jLabelProfileIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProfileIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProfileIconMouseClicked(evt);
            }
        });

        jLabelUsernameHomePage.setText("Username");

        jLabelTotalWallpaperHomePage.setText("Total wallpaper  ");

        jComboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCategory.addActionListener(this::jComboBoxCategoryActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTotalWallpaperHomePage)
                        .addGap(248, 248, 248)
                        .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelProfileIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUsernameHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(632, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelProfileIcon))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabelUsernameHomePage)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jLabelTotalWallpaperHomePage)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanelHomeGallery.setBackground(new java.awt.Color(204, 204, 204));
        jPanelHomeGallery.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPanePublicWallpaperGallery.setViewportView(jPanelHomeGallery);

        getContentPane().add(jScrollPanePublicWallpaperGallery, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelProfileIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProfileIconMouseClicked
        // TODO add your handling code here:        
        if (!isUserLoggedIn){
            JOptionPane.showMessageDialog(this, "Akses Ditolak! Anda harus login terlebih dahulu untuk melihat profil.", "Notice", JOptionPane.INFORMATION_MESSAGE);
            return;
        } 

        this.dispose();

        ProfileFrame profilePage = new ProfileFrame(currentUserId, currentUsername, null);
        profilePage.setVisible(true);
    }//GEN-LAST:event_jLabelProfileIconMouseClicked

    private void jComboBoxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxCategoryActionPerformed

    private void getWallpaperCategoryList () {
        
        String getByCategorySQL = "SELECT DISTINCT LOWER(category) AS category_name FROM artworks";
        
        try (Connection con = DBConnection.getConnection();
            PreparedStatement listCategory = con.prepareStatement(getByCategorySQL)) {
            
            ResultSet resListCategory= listCategory.executeQuery();
            
            jComboBoxCategory.removeAllItems();
            
            while (resListCategory.next()) {
                jComboBoxCategory.addItem(resListCategory.getString("category_name"));
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "gagal mendapat category", "Database Error" ,JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    private void ShowWallpaperGalleryAll () {
        
        jPanelHomeGallery.removeAll();
        jPanelHomeGallery.setLayout(new java.awt.GridLayout(0, 5, 15, 15));
        
        //wallpaper public
        GalleryProvider gallery = new WallpaperPublic();
        
        List<Wallpaper> daftarWallpaper =  gallery.getGalleryWallpaper(currentUserId);
              
        JPanel wrapper = new JPanel(new BorderLayout());        
        wrapper.setBackground(jPanelHomeGallery.getBackground());
        wrapper.add(jPanelHomeGallery, BorderLayout.NORTH);        
        
        for (Wallpaper wp : daftarWallpaper) {
            WallpaperCard card = new WallpaperCard(wp,this); 
            jPanelHomeGallery.add(card);
        }
        
        jScrollPanePublicWallpaperGallery.setViewportView(wrapper);
        
        jPanelHomeGallery.revalidate();
        jPanelHomeGallery.repaint(); 
        
        jLabelTotalWallpaperHomePage.setText("Total Images : " +  GalleryProvider.countWallpaper(daftarWallpaper));
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeFrame(false,0,"Guest").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxCategory;
    private javax.swing.JLabel jLabelProfileIcon;
    private javax.swing.JLabel jLabelTotalWallpaperHomePage;
    private javax.swing.JLabel jLabelUsernameHomePage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelHomeGallery;
    private javax.swing.JScrollPane jScrollPanePublicWallpaperGallery;
    // End of variables declaration//GEN-END:variables
}
