/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import components.WallpaperCard;
import java.sql.*;
import database.DBConnection;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.nio.file.Files;
import java.io.IOException; 
import java.util.List;
import javax.swing.JFileChooser;
import interfaces.GalleryProvider;
import models.Wallpaper;
import javax.swing.JPanel;
import java.awt.*;
import java.nio.file.StandardCopyOption;
import models.WallpaperPrivate;
import dao.UserDAO;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
/**
 *
 * @author Nice
 */
public class ProfileFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProfileFrame.class.getName());

    /**
     * Creates new form ProfileFrame
     */
    private final int currentUserId; 
    private final String currentUsername;
    private models.User currentUser; 
    private boolean isEditPanelVisible = false;
    private boolean isLogin = false;   

    
    public ProfileFrame(int userId, String username, String bio) {
        this.currentUserId = userId; 
        this.currentUsername = username;

        if (currentUserId > 0) {
            isLogin = true;
        }
        
        dao.UserDAO userDAO = new dao.UserDAO();
        this.currentUser = userDAO.getUserById(userId);
        initComponents(); 
        setResizable(false);
        setLocationRelativeTo(null);
        editPanel.setVisible(false);
        editPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        editPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        getContentPane().setBackground(new java.awt.Color(41, 41, 41));       

        jLabelName.setText(username.toUpperCase());

        if (bio == null || bio.isEmpty()) {
            bio = (currentUser != null && currentUser.getBio() != null) ? currentUser.getBio() : "";
        }
        
        jLabelBio.setText(bio);
        this.setTitle(this.currentUser.getDashboardTitle());
        homeBtn.setContentAreaFilled(false);
        uploadBtn.setContentAreaFilled(false);
        
        getWallpaperCategoryList();
        showGalleryWallpaperUser(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        jLabelBio = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        editPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        editBioField = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        editPasswordField = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        editUsernameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        editBtn = new javax.swing.JButton();
        editErrorLabel = new javax.swing.JLabel();
        jScrollPanePrivateWallpaperGallery = new javax.swing.JScrollPane();
        jPanelProfileGallery = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabelBio1 = new javax.swing.JLabel();
        uploadBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxCategory = new javax.swing.JComboBox<>();
        jButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profile Page");
        setPreferredSize(new java.awt.Dimension(1080, 700));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(41, 41, 41));
        jPanel3.setPreferredSize(new java.awt.Dimension(1080, 120));

        jLabelName.setBackground(new java.awt.Color(255, 255, 255));
        jLabelName.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_icon.png"))); // NOI18N
        jLabelName.setText("  USER!");
        jLabelName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNameMouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Welcome! Find ideas you’ll love.");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Discover ideas, save inspiration, and bring your imagination.");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoPixelPaint.png"))); // NOI18N

        homeBtn.setBackground(new java.awt.Color(0, 0, 0));
        homeBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        homeBtn.setText(" Home");
        homeBtn.setAlignmentY(0.0F);
        homeBtn.setBorder(null);
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.addActionListener(this::homeBtnActionPerformed);

        jLabelBio.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelBio.setForeground(new java.awt.Color(204, 204, 204));
        jLabelBio.setText("Discover ideas, save inspiration, and bring your imagination.");

        logoutBtn.setBackground(new java.awt.Color(255, 51, 0));
        logoutBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lgin_con.png"))); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.setAlignmentY(0.0F);
        logoutBtn.setBorder(null);
        logoutBtn.setBorderPainted(false);
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel10)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName)
                            .addComponent(jLabel9)
                            .addComponent(jLabelBio))
                        .addGap(22, 22, 22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 438, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel10)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(21, 21, 21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelBio))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        editPanel.setBackground(new java.awt.Color(41, 41, 41));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bio_icon.png"))); // NOI18N
        jLabel4.setText("Bio");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));

        editBioField.setColumns(20);
        editBioField.setRows(5);
        editBioField.setBorder(null);
        editBioField.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(editBioField, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editBioField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Profile Settings");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        editPasswordField.setBorder(null);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        editUsernameField.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        editUsernameField.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editUsernameField)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editUsernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/username_icon.png"))); // NOI18N
        jLabel1.setText("Username");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pw_icon.png"))); // NOI18N
        jLabel3.setText("Password");

        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);

        editBtn.setBackground(new java.awt.Color(0, 0, 255));
        editBtn.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("Save!");
        editBtn.setBorder(null);
        editBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBtn.addActionListener(this::editBtnActionPerformed);

        editErrorLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        editErrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(130, 130, 130))
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel11)
                .addGap(26, 26, 26)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPanePrivateWallpaperGallery.setBorder(null);

        jPanelProfileGallery.setBackground(new java.awt.Color(41, 41, 41));
        jPanelProfileGallery.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPanePrivateWallpaperGallery.setViewportView(jPanelProfileGallery);

        jPanel2.setBackground(new java.awt.Color(41, 41, 41));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Inspiration Board");

        jLabelBio1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBio1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabelBio1.setForeground(new java.awt.Color(204, 204, 204));
        jLabelBio1.setText("Your space for inspiration.");

        uploadBtn.setBackground(new java.awt.Color(0, 0, 0));
        uploadBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        uploadBtn.setForeground(new java.awt.Color(255, 255, 255));
        uploadBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unggah.png"))); // NOI18N
        uploadBtn.setText(" Uploads");
        uploadBtn.setAlignmentY(0.0F);
        uploadBtn.setBorder(null);
        uploadBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uploadBtn.addActionListener(this::uploadBtnActionPerformed);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Search by category  :");

        jComboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCategory.addActionListener(this::jComboBoxCategoryActionPerformed);

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(this::jButtonResetActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabelBio1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonReset)
                .addGap(76, 76, 76)
                .addComponent(uploadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelBio1))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonReset))
                        .addComponent(uploadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPanePrivateWallpaperGallery)
            .addComponent(editPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPanePrivateWallpaperGallery, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        new HomeFrame(isLogin, currentUserId, currentUsername).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void jLabelNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNameMouseClicked
        // TODO add your handling code here:
        isEditPanelVisible = !isEditPanelVisible;
        editPanel.setVisible(isEditPanelVisible);

        System.out.println("Edit panel visible: " + isEditPanelVisible);
        System.out.println("Panel size: " + editPanel.getSize());

        if (isEditPanelVisible) {
            editPanel.setPreferredSize(null);
            editPanel.setMinimumSize(null);

            editUsernameField.setText(currentUser.getUsername());
            editBioField.setText(currentUser.getBio());
            editPasswordField.setText(currentUser.getPassword());
            editPasswordField.setEchoChar('\u25CF');
            editErrorLabel.setText("");
            jCheckBox1.setSelected(false);
            
            setSize(1080, 900);
            setLocationRelativeTo(null);
        }else{
            editPanel.setPreferredSize(new java.awt.Dimension(0, 0)); 
            editPanel.setMinimumSize(new java.awt.Dimension(0, 0));
            
            setSize(1080, 700);
            setLocationRelativeTo(null);
        }
        getContentPane().revalidate(); 
        getContentPane().repaint();
    }//GEN-LAST:event_jLabelNameMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            editPasswordField.setEchoChar((char) 0); // tampilkan
        } else {
            editPasswordField.setEchoChar('\u25CF'); // sembunyikan
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        String newUsername = editUsernameField.getText().trim();
        String newPassword = new String(editPasswordField.getPassword()).trim();
        String newBio = editBioField.getText().trim();

        if (newUsername.isEmpty()) {
            editErrorLabel.setText("* Username tidak boleh kosong!");
            editErrorLabel.setForeground(java.awt.Color.RED);
            return;
        }

        UserDAO userDAO = new UserDAO();
        boolean success = userDAO.updateProfile(currentUserId, newUsername, newPassword, newBio);

        if (success) {
            editErrorLabel.setText("Profil berhasil diperbarui!");
            editErrorLabel.setForeground(new java.awt.Color(0, 153, 0));
            isEditPanelVisible = false;
            editPanel.setVisible(false);
            editPanel.setPreferredSize(new java.awt.Dimension(0, 0));
            editPanel.setMinimumSize(new java.awt.Dimension(0, 0));
            JOptionPane.showMessageDialog(this, 
                "Profil berhasil diperbarui!\nSilakan login kembali!", 
                "Berhasil", 
                JOptionPane.INFORMATION_MESSAGE);
                new LoginFrame().setVisible(true);
            this.dispose();
            setSize(1080, 700);        
            setLocationRelativeTo(null);
            getContentPane().revalidate();
            getContentPane().repaint();

            jLabelName.setText(newUsername);

            isEditPanelVisible = false;
            editPanel.setVisible(false);
        } else {
            editErrorLabel.setText("* Username sudah dipakai!");
            editErrorLabel.setForeground(java.awt.Color.RED);
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void uploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg"));
        
        int result = fileChooser.showOpenDialog(this);
        
        if (result != JFileChooser.APPROVE_OPTION) {
            return;
        }
        
        File fileWallpaper = fileChooser.getSelectedFile();
        File targetDirectory = new File("src/uploads");
        
        if (!targetDirectory.exists()) {
            targetDirectory.mkdirs();
        }
        
        String title = JOptionPane.showInputDialog(this, "Masukkan Judul Wallpaper:");
        if (title == null) {
            JOptionPane.showMessageDialog(this, "Wallpaper harus diberikan title!");
            return;
        }
        
        String description = JOptionPane.showInputDialog(this, "(Boleh di skip!)Masukkan Deskripsi:");
        
        String category = getValidatedCategoryFromUser();      
        if (category == null) {
            JOptionPane.showMessageDialog(this, "Wallpaper harus diberikan Category!");
            return;
        }
        
        String uniqueFileName = currentUserId + "_" + System.currentTimeMillis() + "_" + (fileWallpaper.getName().replace(" ", "_"));
        File destinationFile = new File(targetDirectory, uniqueFileName);
             
            String insertQuerySQL = "INSERT INTO artworks (title, description, category, image_path, user_id) VALUES (?, ?, ?, ?, ?)";
            try (Connection con = DBConnection.getConnection();
                PreparedStatement AddWallapaperPstmt = con.prepareStatement(insertQuerySQL)) {
                AddWallapaperPstmt.setString(1, title.trim());
                AddWallapaperPstmt.setString(2, description != null ? description.trim() : "");
                AddWallapaperPstmt.setString(3, category.trim().toLowerCase());
                AddWallapaperPstmt.setString(4, uniqueFileName);
                AddWallapaperPstmt.setInt(5, currentUserId);
                
                // Proses copy file secara langsung ke folder uploads
                Files.copy(fileWallpaper.toPath(), destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                AddWallapaperPstmt.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Wallpaper berhasil diunggah!");
                getWallpaperCategoryList();
                showGalleryWallpaperUser();
            }
            
            catch (IOException | SQLException e) {
                if (destinationFile.exists()) {
                   destinationFile.delete();
                }
                JOptionPane.showMessageDialog(this, "Gagal memproses unggahan: " + e.getMessage());
            }       
    }//GEN-LAST:event_uploadBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void jComboBoxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryActionPerformed
        // TODO add your handling code here:
        String selectedCategory = (String)jComboBoxCategory.getSelectedItem();

        GalleryProvider gallery = new WallpaperPrivate();
        List<Wallpaper> daftarWallpaper =  gallery.getGalleryWallpaper(currentUserId);
        List<Wallpaper> filteredDaftarWallpaper = gallery.filterByCategory(daftarWallpaper, selectedCategory);

        jPanelProfileGallery.removeAll();

        for (Wallpaper wp : filteredDaftarWallpaper) {
            WallpaperCard card = new WallpaperCard(wp, currentUserId, this);
            jPanelProfileGallery.add(card);
        }

        jPanelProfileGallery.revalidate();
        jPanelProfileGallery.repaint();
    }//GEN-LAST:event_jComboBoxCategoryActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        showGalleryWallpaperUser();
    }//GEN-LAST:event_jButtonResetActionPerformed
   
    private String getValidatedCategoryFromUser() {
           
        ArrayList<String> listCategory = new ArrayList<>();
        
        for (int i = 0; i < jComboBoxCategory.getItemCount(); i++) {
            Object item = jComboBoxCategory.getItemAt(i);
            if (item != null) {
                listCategory.add(item.toString());
            }
        }

        String optionCategoryBaru = "+ Tambah Kategori Baru...";
        listCategory.add(optionCategoryBaru);
        
        JComboBox <String> comboBoxInputCategory = new JComboBox<>(listCategory.toArray(new String[0]));
        
        //Lamda Function
        comboBoxInputCategory.addActionListener(e -> {
            
            String result;          
            String selectedCategory = (String) comboBoxInputCategory.getSelectedItem();
            
            if (selectedCategory.equals(optionCategoryBaru)) {

                String categoryBaru = JOptionPane.showInputDialog(this, "Masukkan Nama Kategori Baru:");

                if (categoryBaru == null || categoryBaru.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Kategori baru tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    comboBoxInputCategory.setSelectedIndex(0);
                    return;
                }

                String input = categoryBaru.toLowerCase().replaceAll("\\s+", "");
                String categoryCheck = "";
                boolean isDuplicate = false;

                for (String exisingCategory : listCategory) {                
                    if (!exisingCategory.equals(optionCategoryBaru)){
                        
                        String category = exisingCategory.toLowerCase().replaceAll("\\s+", "");
                        if (input.equals(category)) {
                            isDuplicate = true;
                            categoryCheck = exisingCategory;
                            break;
                        }
                        
                    }          
                }

                if (isDuplicate) {
                    JOptionPane.showMessageDialog(this, 
                        "Kategori " + categoryBaru + " sama dengan " + categoryCheck + " yang sudah ada.\n" +
                        "Silakan pilih langsung '" + categoryCheck + "' pada Dropdown!", 
                        "Kategori Sudah Ada", JOptionPane.WARNING_MESSAGE);
                }
                
                result = (Character.toUpperCase(input.charAt(0)) + input.substring(1)).trim();
                int indexCategoryBaru = comboBoxInputCategory.getItemCount() - 1 ;               
                comboBoxInputCategory.insertItemAt(result,indexCategoryBaru);
                comboBoxInputCategory.setSelectedItem(result);
            }                      
        });

        int dialogConfirm = JOptionPane.showConfirmDialog(
            this, 
            comboBoxInputCategory, 
            "Pilih Kategori Wallpaper", 
            JOptionPane.OK_CANCEL_OPTION, 
            JOptionPane.PLAIN_MESSAGE
        );
        
        if (dialogConfirm == JOptionPane.OK_OPTION) {
            String finalSelection = (String) comboBoxInputCategory.getSelectedItem();

            if (optionCategoryBaru.equals(finalSelection)) {
                JOptionPane.showMessageDialog(this, "Silakan pilih kategori yang valid!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return null;
            }

            return finalSelection.toLowerCase();
        }

        return null;    
    }
    
    private void getWallpaperCategoryList () {        
        String getByCategorySQL = "SELECT DISTINCT LOWER(category) AS category_name FROM artworks";       
        try (Connection con = DBConnection.getConnection();
            PreparedStatement listCategory = con.prepareStatement(getByCategorySQL)) {
            
            ResultSet resListCategory= listCategory.executeQuery();          
            jComboBoxCategory.removeAllItems();
            
            while (resListCategory.next()) {
                jComboBoxCategory.addItem(Character.toUpperCase(resListCategory.getString("category_name").charAt(0)) + resListCategory.getString("category_name").substring(1));
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "gagal mendapat category", "Database Error" ,JOptionPane.ERROR_MESSAGE);
        }       
    }
    
    public void showGalleryWallpaperUser() {
        jPanelProfileGallery.removeAll();
        jPanelProfileGallery.setLayout(new GridLayout(0, 4, 15, 15));
        jPanelProfileGallery.setBorder(BorderFactory.createEmptyBorder(10, 20, 50, 30));
        
        //gallery private
        GalleryProvider gallery = new WallpaperPrivate();
        
        List<Wallpaper> daftarWallpaper = gallery.getGalleryWallpaper(currentUserId);

        for (Wallpaper wp : daftarWallpaper) {
            WallpaperCard card = new WallpaperCard(wp, currentUserId, ProfileFrame.this); 
            jPanelProfileGallery.add(card);
        }
        
        JPanel wrapper = new JPanel(new BorderLayout());        
        wrapper.setBackground(jPanelProfileGallery.getBackground());
        wrapper.add(jPanelProfileGallery, BorderLayout.NORTH);
        
        jScrollPanePrivateWallpaperGallery.setViewportView(wrapper);        
        
        wrapper.revalidate();        
        wrapper.repaint(); 
        jPanelProfileGallery.revalidate();
        jPanelProfileGallery.repaint();              
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProfileFrame(3,"","").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea editBioField;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel editErrorLabel;
    private javax.swing.JPanel editPanel;
    private javax.swing.JPasswordField editPasswordField;
    private javax.swing.JTextField editUsernameField;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBoxCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBio;
    private javax.swing.JLabel jLabelBio1;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelProfileGallery;
    private javax.swing.JScrollPane jScrollPanePrivateWallpaperGallery;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton uploadBtn;
    // End of variables declaration//GEN-END:variables

    private void setTitle() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
