/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import components.WallpaperCard;
import interfaces.GalleryProvider;
import models.Wallpaper;
import javax.swing.*;
import java.awt.*;
import java.util.List;
import java.sql.*;
import database.DBConnection;
import models.WallpaperPrivate;

/**
 *
 * @author Nice
 */
public class PublicProfileFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PublicProfileFrame.class.getName());

    /**
     * Creates new form PublicProfileFrame
     */
    
    private final int profileUserId;
    private final int currentUserId;
    
    public PublicProfileFrame(int profileUserId, int currentUserId) {
        this.profileUserId = profileUserId;
        this.currentUserId = currentUserId;

        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(41, 41, 41));
        
        jScrollPanePublicWallpaperGallery.setBorder(null);
        jScrollPanePublicWallpaperGallery.getVerticalScrollBar().setPreferredSize(new java.awt.Dimension(0, 0));
        jScrollPanePublicWallpaperGallery.getHorizontalScrollBar().setPreferredSize(new java.awt.Dimension(0, 0));
        jScrollPanePublicWallpaperGallery.getVerticalScrollBar().setUnitIncrement(20);
        jScrollPanePublicWallpaperGallery.setWheelScrollingEnabled(true);
        
        jButtonReset.setContentAreaFilled(false);
        bckBtn.setContentAreaFilled(false);
        bckBtn.addActionListener(e -> this.dispose());
        loadProfileData();
        loadCategoryList();
        loadGallery();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bioLabel = new javax.swing.JLabel();
        bckBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        usernameLabel1 = new javax.swing.JLabel();
        bioLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxCategory = new javax.swing.JComboBox<>();
        jButtonReset = new javax.swing.JButton();
        jScrollPanePublicWallpaperGallery = new javax.swing.JScrollPane();
        jPanelHomeGallery = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 660));

        jPanel1.setBackground(new java.awt.Color(41, 41, 41));

        usernameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("Danadyaksa_Rabbani123");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoPixelPaint.png"))); // NOI18N

        bioLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        bioLabel.setForeground(new java.awt.Color(205, 205, 205));
        bioLabel.setText("Always With Me 0_0");

        bckBtn.setBackground(new java.awt.Color(41, 41, 41));
        bckBtn.setForeground(new java.awt.Color(255, 255, 255));
        bckBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bck_icon.png"))); // NOI18N
        bckBtn.setBorder(null);
        bckBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(bckBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(bckBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(usernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bioLabel)
                        .addGap(12, 12, 12)))
                .addGap(35, 35, 35))
        );

        jPanel2.setBackground(new java.awt.Color(41, 41, 41));

        usernameLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        usernameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel1.setText("Explore Boards");

        bioLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        bioLabel1.setForeground(new java.awt.Color(205, 205, 205));
        bioLabel1.setText("Discover ideas from others.");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Search by category  :");

        jComboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCategory.addActionListener(this::jComboBoxCategoryActionPerformed);

        jButtonReset.setBackground(new java.awt.Color(41, 41, 41));
        jButtonReset.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(this::jButtonResetActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bioLabel1)
                    .addComponent(usernameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonReset)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReset))
                .addGap(0, 23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usernameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bioLabel1)
                .addContainerGap())
        );

        jScrollPanePublicWallpaperGallery.setBackground(new java.awt.Color(41, 41, 41));
        jScrollPanePublicWallpaperGallery.setBorder(null);
        jScrollPanePublicWallpaperGallery.setAlignmentX(0.0F);
        jScrollPanePublicWallpaperGallery.setAlignmentY(0.0F);
        jScrollPanePublicWallpaperGallery.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPanePublicWallpaperGallery.setRowHeaderView(null);

        jPanelHomeGallery.setBackground(new java.awt.Color(41, 41, 41));
        jPanelHomeGallery.setAlignmentX(0.0F);
        jPanelHomeGallery.setAlignmentY(0.0F);
        jPanelHomeGallery.setLayout(new java.awt.GridLayout(1, 3));
        jScrollPanePublicWallpaperGallery.setViewportView(jPanelHomeGallery);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPanePublicWallpaperGallery)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPanePublicWallpaperGallery, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryActionPerformed
        // TODO add your handling code here:
        String selectedCategory = (String) jComboBoxCategory.getSelectedItem();
        if (selectedCategory == null) return;

        GalleryProvider gallery = new WallpaperPrivate();
        List<Wallpaper> daftarWallpaper = gallery.getGalleryWallpaper(profileUserId); 
        List<Wallpaper> filteredDaftarWallpaper = gallery.filterByCategory(daftarWallpaper, selectedCategory);

        jPanelHomeGallery.removeAll();
        jPanelHomeGallery.setLayout(new java.awt.GridLayout(0, 4, 10, 15));
        jPanelHomeGallery.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 33, 20, 15));

        for (Wallpaper wp : filteredDaftarWallpaper) {
            WallpaperCard card = new WallpaperCard(wp, currentUserId, this);
            jPanelHomeGallery.add(card);
        }

        JPanel wrapper = new JPanel(new BorderLayout());
        wrapper.setBackground(jPanelHomeGallery.getBackground());
        wrapper.add(jPanelHomeGallery, BorderLayout.NORTH);

        jScrollPanePublicWallpaperGallery.setViewportView(wrapper);
        jPanelHomeGallery.revalidate();
        jPanelHomeGallery.repaint();
    }//GEN-LAST:event_jComboBoxCategoryActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        loadGallery();
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void loadCategoryList() {        
        String getByCategorySQL = "SELECT DISTINCT LOWER(category) AS category_name FROM artworks";       
        try (Connection con = DBConnection.getConnection();
            PreparedStatement listCategory = con.prepareStatement(getByCategorySQL)) {
            
            ResultSet resListCategory= listCategory.executeQuery();
            
            jComboBoxCategory.removeAllItems();
            
            while (resListCategory.next()) {            
                jComboBoxCategory.addItem(Character.toUpperCase(resListCategory.getString("category_name").charAt(0)) + resListCategory.getString("category_name").substring(1));
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "gagal mendapat category", "Database Error" ,JOptionPane.ERROR_MESSAGE);
        }       
    } 
    
    private void loadGallery() {
        jPanelHomeGallery.removeAll();
        jPanelHomeGallery.setLayout(new java.awt.GridLayout(0, 4, 10, 15));
        jPanelHomeGallery.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 33, 20, 15));

        GalleryProvider gallery = new models.WallpaperPrivate();
        List<Wallpaper> daftarWallpaper = gallery.getGalleryWallpaper(profileUserId);

        for (Wallpaper wp : daftarWallpaper) {
            WallpaperCard card = new WallpaperCard(wp, currentUserId, this);
            jPanelHomeGallery.add(card);
        }

        JPanel wrapper = new JPanel(new BorderLayout());
        wrapper.setBackground(jPanelHomeGallery.getBackground());
        wrapper.add(jPanelHomeGallery, BorderLayout.NORTH);

        jScrollPanePublicWallpaperGallery.setViewportView(wrapper);
        jScrollPanePublicWallpaperGallery.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        jScrollPanePublicWallpaperGallery.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPanePublicWallpaperGallery.getVerticalScrollBar().setUnitIncrement(20);

        jPanelHomeGallery.revalidate();
        jPanelHomeGallery.repaint();
    }
    
    private void loadProfileData() {
        String sql = "SELECT username, bio FROM users WHERE id = ?";
        try (Connection con = DBConnection.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, profileUserId);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String username = rs.getString("username");
                String bio = rs.getString("bio");

                usernameLabel.setText(username.toUpperCase());
                bioLabel.setText(bio != null && !bio.isEmpty() ? bio : "No bio yet.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PublicProfileFrame(2, -1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bckBtn;
    private javax.swing.JLabel bioLabel;
    private javax.swing.JLabel bioLabel1;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JComboBox<String> jComboBoxCategory;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelHomeGallery;
    private javax.swing.JScrollPane jScrollPanePublicWallpaperGallery;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel1;
    // End of variables declaration//GEN-END:variables
}
