/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import database.DBConnection;
import interfaces.GalleryProvider;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import models.Wallpaper;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JComboBox;

/**
 *
 * @author Nice
 */
public class UpdateFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateFrame.class.getName());

    /**
     * Creates new form DetailFrame
     */

    private final int currentUserId;
    private final Wallpaper wallpaperInfo;
    private final JFrame mainFrame;

    public UpdateFrame(Wallpaper wp, int currentUserId, JFrame mainFrame, File fileGambar) {
        this.wallpaperInfo = wp;
        this.mainFrame = mainFrame;
        this.currentUserId = currentUserId;

        initComponents();
        this.setTitle(wallpaperInfo.getTitle());
        
        jButtonCancel.setContentAreaFilled(false);
        jButtonConfirmEdit.setContentAreaFilled(false);

        getContentPane().setBackground(new java.awt.Color(41, 41, 41));
        getWallpaperCategoryList();
        showWallpaperDetail(fileGambar);   
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonConfirmEdit = new javax.swing.JButton();
        jLabelUploaderName = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jTextFieldDescription = new javax.swing.JTextField();
        jTextFieldImageTitle = new javax.swing.JTextField();
        jComboBoxCategory = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabelImage.setBackground(new java.awt.Color(255, 255, 255));
        jLabelImage.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImage.setMaximumSize(new java.awt.Dimension(800, 500));
        jLabelImage.setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel2.setBackground(new java.awt.Color(41, 41, 41));
        jPanel2.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 165));

        jButtonCancel.setBackground(new java.awt.Color(41, 41, 41));
        jButtonCancel.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setText("Cancel");
        jButtonCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancel.addActionListener(this::jButtonCancelActionPerformed);

        jButtonConfirmEdit.setBackground(new java.awt.Color(41, 41, 41));
        jButtonConfirmEdit.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jButtonConfirmEdit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConfirmEdit.setText("Ok");
        jButtonConfirmEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonConfirmEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConfirmEdit.addActionListener(this::jButtonConfirmEditActionPerformed);

        jLabelUploaderName.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jLabelUploaderName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUploaderName.setText("username");
        jLabelUploaderName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelDate.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jLabelDate.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDate.setText("date");

        jTextFieldDescription.setText("Description");

        jTextFieldImageTitle.setText("Image_name");

        jComboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCategory.addActionListener(this::jComboBoxCategoryActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUploaderName)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonConfirmEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCategory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldDescription, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldImageTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTextFieldImageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUploaderName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirmEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryActionPerformed
        // TODO add your handling code here:
        String selected = (String) jComboBoxCategory.getSelectedItem();
        if (selected != null  && selected.equals("+ Tambah Kategori Baru...")) {
            String newCategory = getValidatedCategoryFromUser();       
            if (newCategory != null) {
                jComboBoxCategory.insertItemAt(newCategory, jComboBoxCategory.getItemCount() - 1);
                jComboBoxCategory.setSelectedItem(newCategory);
            } else {
                jComboBoxCategory.setSelectedIndex(0);
            }        
        }
    }//GEN-LAST:event_jComboBoxCategoryActionPerformed

    private void jButtonConfirmEditActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:   
        String updatedImageTitle = jTextFieldImageTitle.getText().trim();
        String updatedDesc = jTextFieldDescription.getText().trim();
        String updatedCategory = (String) jComboBoxCategory.getSelectedItem();
        
        if (updatedImageTitle.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Judul tidak boleh kosong!", "Warning!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (updatedCategory == null || updatedCategory.equals("+ Tambah Kategori Baru...")) {
            JOptionPane.showMessageDialog(this, "Silakan pilih kategori yang valid!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String updateSQL = "UPDATE artworks SET title = ?, description = ?, category = ? WHERE id = ?";
   
        try (Connection con = DBConnection.getConnection();
            PreparedStatement updateWallpaper = con.prepareStatement(updateSQL)) {
            
            updateWallpaper.setString(1,updatedImageTitle);
            updateWallpaper.setString(2,updatedDesc);
            updateWallpaper.setString(3,updatedCategory);
            updateWallpaper.setInt(4,wallpaperInfo.getId());
            
            int updateSucess = updateWallpaper.executeUpdate();
            
            if (updateSucess > 0){
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
                this.dispose();
            }      
            
            if(this.mainFrame instanceof ManageFrame manageFrame)manageFrame.showWallpaperGalleryAll();
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "gagal melakukan update", "Error" ,JOptionPane.ERROR_MESSAGE);
        } 
        
        
    }

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.dispose();
    }
    
    private String getValidatedCategoryFromUser() {
        
        ArrayList<String> listCategory = new ArrayList<>();     
        for (int i = 0; i < jComboBoxCategory.getItemCount(); i++) {
            Object item = jComboBoxCategory.getItemAt(i);
            if (item != null && !item.equals("+ Tambah Kategori Baru...")) {
                listCategory.add(item.toString());
            }
        }
        
        String newCategory = JOptionPane.showInputDialog(this, "Masukkan Nama Kategori Baru:");
        
        String normalizedInput = newCategory.trim().substring(0, 1).toUpperCase() + newCategory.trim().substring(1).toLowerCase();
        
        for (String categoryName : listCategory) {
            if (categoryName.equalsIgnoreCase(normalizedInput)) {
                JOptionPane.showMessageDialog(this, "Kategori '" + normalizedInput + "' sudah ada!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return null;
            }
        }
        
       return newCategory; 
       
    }

    private void getWallpaperCategoryList() {        
        String getByCategorySQL = "SELECT DISTINCT LOWER(category) AS category_name FROM artworks";       
        try (Connection con = DBConnection.getConnection();
            PreparedStatement listCategory = con.prepareStatement(getByCategorySQL)) {
            
            jComboBoxCategory.removeAllItems();
            ResultSet resListCategory = listCategory.executeQuery();             
            
            while (resListCategory.next()) {            
                jComboBoxCategory.addItem(Character.toUpperCase(resListCategory.getString("category_name").charAt(0)) + resListCategory.getString("category_name").substring(1));
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "gagal mendapat category", "Database Error" ,JOptionPane.ERROR_MESSAGE);
        }  
        
        jComboBoxCategory.addItem("+ Tambah Kategori Baru...");
    }
    
    private void showWallpaperDetail(File fileGambar) {
        
        if (wallpaperInfo != null) {

            String uploader = GalleryProvider.getUsernameFromId(wallpaperInfo.getUserId());
            String uploaderCapitalized = uploader.substring(0, 1).toUpperCase() + uploader.substring(1);
            String title = wallpaperInfo.getTitle();
            String[] words = title.split(" ");
            StringBuilder capitalizedTitle = new StringBuilder();

            for (String word : words) {
                if (!word.isEmpty()) {
                    capitalizedTitle.append(word.substring(0, 1).toUpperCase())
                            .append(word.substring(1).toLowerCase())
                            .append(" ");
                }
            }
            String rawDate = wallpaperInfo.getTimeAdded().substring(0, wallpaperInfo.getTimeAdded().indexOf(' '));
            java.time.LocalDate date = java.time.LocalDate.parse(rawDate);
            java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd MMMM yyyy", new java.util.Locale("id", "ID"));
            String formattedDate = date.format(formatter);

            jTextFieldImageTitle.setText(capitalizedTitle.toString().trim());
            jLabelUploaderName .setText("<html><b>Uploaded By:</b>&nbsp;&nbsp;&nbsp;&nbsp;" + uploaderCapitalized + "</html>");
            jComboBoxCategory.setSelectedItem(wallpaperInfo.getCategory());
            jTextFieldDescription.setText(wallpaperInfo.getDescription());
            jLabelDate.setText("<html><b>Created At:</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" + formattedDate + "</html>");

            try {
                    ImageIcon selectedIcon;
                    if (fileGambar.exists() && this.wallpaperInfo.getImagePath() != null) {
                        selectedIcon = new ImageIcon(fileGambar.getAbsolutePath());
                    } else {
                        selectedIcon = new ImageIcon("src/uploads/default.jpg");
                    }

                    int labelWidth = jLabelImage.getWidth();
                    int labelHeight = jLabelImage.getHeight();

                    if (labelWidth == 0) labelWidth = 800;
                    if (labelHeight == 0) labelHeight = 500;

                    double imgWidth = selectedIcon.getIconWidth();
                    double imgHeight = selectedIcon.getIconHeight();
                    double ratio = Math.min(labelWidth / imgWidth, labelHeight / imgHeight);

                    int newWidth = (int) (imgWidth * ratio);
                    int newHeight = (int) (imgHeight * ratio);

                    Image scaledImage = selectedIcon.getImage().getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
                    jLabelImage.setIcon(new ImageIcon(scaledImage));

                } catch (Exception e) {
                    e.printStackTrace();
                }

        } else {
            System.out.print("Error");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonConfirmEdit;
    private javax.swing.JComboBox<String> jComboBoxCategory;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelUploaderName;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldImageTitle;
    // End of variables declaration//GEN-END:variables
}
