/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;
import models.Wallpaper;
import javax.swing.JFrame;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import static models.WallpaperPublic.getUsernameById;
import views.DetailFrame;

/**
 *
 * @author user
 */
public class WallpaperCard extends javax.swing.JPanel {

    /**
     * Creates new form WallpaperCard
     */
    
   private final Wallpaper wallpaperInfo;
   private final JFrame mainFrame;
   private final int currentUserId;
   private final String currentUsername;
            
   //ketika login
    public WallpaperCard(Wallpaper wp, int currentUserId, String currentUsername, JFrame mainFrame) {
        
        this.wallpaperInfo = wp;
        this.currentUserId = currentUserId;
        this.currentUsername = currentUsername;
        this.mainFrame = mainFrame;
               
        initComponents();
        showWallpaperDetail();
        
        Dimension ukuranTetap = new Dimension(200, 260);
        this.setPreferredSize(ukuranTetap);
        this.setMinimumSize(ukuranTetap);
        this.setMaximumSize(ukuranTetap);               
    }
    
    //tidak login
    public WallpaperCard(Wallpaper wp, JFrame mainFrame) {
        this.currentUserId = -1;
        this.currentUsername = "Guest";
        
        this.wallpaperInfo = wp;
        this.mainFrame = mainFrame;
               
        initComponents();
        showWallpaperDetail();
        getPublicWallpaperCardDetail();
        
        Dimension ukuranTetap = new Dimension(200, 260);
        this.setPreferredSize(ukuranTetap);
        this.setMinimumSize(ukuranTetap);
        this.setMaximumSize(ukuranTetap);             
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImage = new javax.swing.JLabel();
        jPanelCardInfo = new javax.swing.JPanel();
        jLabelImageTitle = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelCategory = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jLabelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImage.setToolTipText("");
        jLabelImage.setPreferredSize(new java.awt.Dimension(180, 220));
        jLabelImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImageMouseClicked(evt);
            }
        });
        add(jLabelImage, java.awt.BorderLayout.CENTER);

        jPanelCardInfo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCardInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelCardInfo.setMaximumSize(new java.awt.Dimension(180, 100));
        jPanelCardInfo.setMinimumSize(new java.awt.Dimension(180, 100));
        jPanelCardInfo.setName(""); // NOI18N
        jPanelCardInfo.setPreferredSize(new java.awt.Dimension(180, 100));
        jPanelCardInfo.setVerifyInputWhenFocusTarget(false);
        jPanelCardInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCardInfoMouseClicked(evt);
            }
        });

        jLabelImageTitle.setText("title");

        jLabelUserName.setText("username");

        jLabelCategory.setText("kategory");

        jLabelDate.setText("date added");

        javax.swing.GroupLayout jPanelCardInfoLayout = new javax.swing.GroupLayout(jPanelCardInfo);
        jPanelCardInfo.setLayout(jPanelCardInfoLayout);
        jPanelCardInfoLayout.setHorizontalGroup(
            jPanelCardInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCardInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCardInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelDate, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jLabelCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelImageTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(252, 252, 252))
        );
        jPanelCardInfoLayout.setVerticalGroup(
            jPanelCardInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCardInfoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelImageTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDate)
                .addContainerGap())
        );

        add(jPanelCardInfo, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jLabelImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImageMouseClicked
        // TODO add your handling code here:
        try {
            
            File fileGambar = new File("src/uploads/" + this.wallpaperInfo.getImagePath());
            
            DetailFrame detail = new DetailFrame(this.wallpaperInfo, this.currentUserId, this.currentUsername, this.mainFrame, fileGambar);
            detail.setVisible(true);
            
        } catch (Exception e) {
            
            e.printStackTrace();
            
        }
    }//GEN-LAST:event_jLabelImageMouseClicked

    private void jPanelCardInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCardInfoMouseClicked
        // TODO add your handling code here:
        try { 
            
            File fileGambar = new File("src/uploads/" + this.wallpaperInfo.getImagePath());
            
            DetailFrame detail = new DetailFrame(this.wallpaperInfo, this.currentUserId, this.currentUsername, this.mainFrame, fileGambar);
            detail.setVisible(true);

        } catch (Exception e) { 
            
            e.printStackTrace();
            
        }
    }//GEN-LAST:event_jPanelCardInfoMouseClicked

    private void getPublicWallpaperCardDetail () {
        jLabelImageTitle.setText(wallpaperInfo.getTitle());
        jLabelUserName.setText("Uploaded By: " + getUsernameById(wallpaperInfo.getUserId()));
        jLabelCategory.setText(wallpaperInfo.getCategory());
        jLabelDate.setText("Created At: " + wallpaperInfo.getTimeAdded().substring(0, wallpaperInfo.getTimeAdded().indexOf(' ')));

    }
    
    private void showWallpaperDetail(){
        
        int lebar = 310;
        int panjang = 280;
        
        
        if (wallpaperInfo != null) {
            jLabelImageTitle.setText(wallpaperInfo.getTitle());
            jLabelUserName.setText("Uploaded By: " + currentUsername);
            jLabelCategory.setText(wallpaperInfo.getCategory());
            jLabelDate.setText("Created At: " + wallpaperInfo.getTimeAdded().substring(0, wallpaperInfo.getTimeAdded().indexOf(' ')));
           
            try {
                
                    File fileGambar = new File("src/uploads/" + this.wallpaperInfo.getImagePath());
                
                    if (fileGambar.exists()) {
                        
                        ImageIcon originalIcon = new ImageIcon(fileGambar.getAbsolutePath());

                        Image scaledImage = originalIcon.getImage().getScaledInstance(lebar, panjang, Image.SCALE_SMOOTH);

                        jLabelImage.setIcon(new ImageIcon(scaledImage));
                        
                    } else {
                        
                        ImageIcon defaultlIcon = new ImageIcon("src/uploads/default.jpg");
                        
                        Image scaledImage = defaultlIcon.getImage().getScaledInstance(lebar, panjang, Image.SCALE_SMOOTH);

                        jLabelImage.setIcon(new ImageIcon(scaledImage));
                        
                    }
                    
                } catch (Exception e) {
                    e.printStackTrace();
                }
            
        } else {
            System.out.print("Error");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCategory;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelImageTitle;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanelCardInfo;
    // End of variables declaration//GEN-END:variables
}
